name: build-and-test

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21.0.2
          java-package: jdk+fx
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - name: Build and Test
        run: |
          sbt -v update compile
          sbt -v test
